### ISSUE TITLE
Cloud Recordings: Meeting response should not be paginated

### ISSUE THREAD

**Issue by michael-aj-kennedy** [Jericho/ZoomNet#101]
The `GetRecordingsAsync()` command within the `CloudRecordings` class requires users to pass in paging parameters and parses the response in the same manner.

However, the response from Zoom is not paginated - This makes sense as we wouldn't expect there to be enough recordings on a single webinar to justify pagination.  Unfortunately this means that ZoomNet is returning an empty object when this function is called.

Looks like this code was a copy & paste of GetRecordingsForUserAsync().

**Comment by Jericho** [comment]
You're right, this method should not be paginated. You're also probably right that it was copy/paste of GetRecordingsForUser because even the description of the method says `Retrieve all cloud recordings for a **user**`.

Sorry about that, I'll get it fixed.

**Comment by Jericho** [comment]
I just realized that you beat me to it: you already submitted a PR to resolve this issue. Thank you for doing that.

**Comment by michael-aj-kennedy** [comment]
> I just realized that you beat me to it: you already submitted a PR to resolve this issue. Thank you for doing that.

No problem, happy to help :)
