### ISSUE TITLE
OAuthTokenHandler hangs after exception on subsequent calls

### ISSUE THREAD

**Issue by infinite-looper** [Jericho/ZoomNet#109]
Hi,

We are integrating this great library in a .NET Core server to server application. 

The library hangs after an exception (such as Invalid Token!) during the refresh of the token on subsequent calls. The following code fixes it in OAuthTokenHandler (with the missing try). A quick patch would be immensely appreciated.

It seems like not releasing the ReaderWriterLockSlim read lock creates problems when exceptions occur.

(I mistakenly posted this in Discussions as well, can't seem to be able to delete it...)

![image](https://user-images.githubusercontent.com/10427373/109364662-47fd3400-785d-11eb-861d-fd2286877825.png)

**Comment by Jericho** [comment]
Thank you for bringing this to my attention and, more importantly, for investing the time to investigate the situation and to propose a solution. Your suggestion seems reasonable at first glance but I will spend some time attempting to reproduce the problem and testing your solution.

Another developer recently reported a `LockRecursionException` problem in situations that seemed random and intermittent to him and he was unable to provide steps to reproduce so I was not able to figure out what was causing the exception. I bet it is exactly the same problem you discovered.

P.S.: I deleted the discussion that was created by mistake

**Comment by Jericho** [comment]
I confirm that I am able to reproduce the problem as you describe it.  I was also able to write a unit test to consistently reproduce and your proposed solution works perfectly.
