### ISSUE TITLE
0.22 RedirectUri not sent to Zoom OAuthTokenHandler

### ISSUE THREAD

**Issue by infinite-looper** [Jericho/ZoomNet#110]
Hi,

Thanks for the quick fix on the lock!

It seems like the PR with the redirecturi was overriden with the lock fix. 

Line 76 has disappeared!

if (!string.IsNullOrEmpty(_connectionInfo.RedirectUri)) requestUrl += $"&redirect_uri={_connectionInfo.RedirectUri}";

Could you hotfix it please?

**Comment by Jericho** [comment]
That's probably my fault. There was a conflict when I merged the PR and the fix and I didn't notice that a line of code was dropped.

**Comment by infinite-looper** [comment]
Merci beaucoup!

You are making me and some random PM happy here.

Thanks again.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Jericho<mailto:notifications@github.com>
Envoyé le :February 27, 2021 4:39 PM
À : Jericho/ZoomNet<mailto:ZoomNet@noreply.github.com>
Cc : infinite-looper<mailto:mgosset@hotmail.com>; Author<mailto:author@noreply.github.com>
Objet :Re: [Jericho/ZoomNet] 0.22 RedirectUri not sent to Zoom OAuthTokenHandler (#110)


Closed #110<https://github.com/Jericho/ZoomNet/issues/110> via db280e8<https://github.com/Jericho/ZoomNet/commit/db280e82f6ea96e96811a2498788944cfb09c732>.

**Comment by Jericho** [comment]
Fix is being published to nuget as we speak. Typically it takes 10-15 minutes for NuGet to index it and make it publicly available.
