### ISSUE TITLE
Add Registrant - Id field

### ISSUE THREAD

**Issue by Julie-House** [Jericho/ZoomNet#111]
The return object from AddRegistrant does not return a 'Registrant'. This means the model binding is incorrect and the Webinar Id is being put into the Registrant Id field. 
This is the object returned by Zoom.
```json
{
  "type": "object",
  "properties": {
    "registrant_id": {
      "type": "string",
      "description": "Registrant ID"
    },
    "id": {
      "type": "string",
      "description": "Webinar ID"
    },
    "topic": {
      "type": "string",
      "description": "Topic",
      "maxLength": 200
    },
    "start_time": {
      "type": "string",
      "format": "date-time",
      "description": "Start time"
    },
    "join_url": {
      "type": "string",
      "description": "Unique URL for this registrant to join the Webinar. This URL should only be shared with the registrant for whom the API request was made."
    }
  }
}
```

Currently, I will need to make a second call to find the registrant via their email address, to retrieve their actual registrant id which can be used for future actions, e.g. approve or deny.

**Comment by Jericho** [comment]
You're right, `Webinars.AddRegistrant` does not return a "registrant" JSON object. I'll create a new model class called something like "RegistrantInfo".

**Comment by Jericho** [comment]
Along the same vein I think we have a similar problem with `Webinars.AddPanelist` and `Webinars.AddPanelists`. The Zoom API does not return a "panelist" JSON object. In fact, according to documentation, it doesn't even return the ID of the newly added panelist(s).

**Comment by Julie-House** [comment]
That's rather interesting. You're then forced to list all panelists to find out their ids to remove an individual one.

Thankfully our integration doesn't require that ability (yet). Who knows what the future will hold though!
