### ISSUE TITLE
Past Webinars Absentee List

### ISSUE THREAD

**Issue by michael-aj-kennedy** [Jericho/ZoomNet#112]
When calling `PastWebinars.GetAbsenteesAsync` ZoomNet returns a list of `Participant` objects, however it should be returning a list  of `Registrant` objects.

https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinarabsentees

**Comment by Jericho** [comment]
You are absolutely correct. I'll get it fixed.

**Comment by michael-aj-kennedy** [comment]
Brilliant, thank you
