### ISSUE TITLE
New resource: DataCompliance

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#119]
It was recently pointed out to me that "data compliance" is missing from ZoomNet: #118

**Comment by Jericho** [comment]
I published a beta [here](https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.26.0-datacompliance-r0017). Can you try it out and let me know if it works as expected?

**Comment by infinite-looper** [comment]
Thanks for the beta. On the IDataCompliance.NotifyAsync, the parameter "secret" is not part of the API as far as I can tell. Any reason why you added it?

Also, what a weird API call from Zoom that requires you to send the received object back to them.

**Comment by Jericho** [comment]
> On the IDataCompliance.NotifyAsync, the parameter "secret" is not part of the API as far as I can tell. Any reason why you added it?

The secret is necessary to fulfill the following: `Make a POST request to https://api.zoom.us/oauth/data/compliance and use Basic Auth with Client ID and Secret for authentication.`. 

The developer provided `ClientSecret` when setting up the OAuthConnectionInfo which I could potentially use as the secret but what if the developer is using JWT? The `JwtConnectionInfo` class expects a `ApiSecret` parameter but I have no idea if that's the same "secret" that the data compliance is expecting. That's why I thought it would be simpler to simply ask the developer to provide the secret as a parameter of the `NotifyAsync` method. Of course, I don't want to ask for information that is not necessary so I'm open to discuss how to improve. Can you think of a better alternative?

> Also, what a weird API call from Zoom that requires you to send the received object back to them.

I wholeheartedly agree! I actually struggled to figure out this data would be passed to the `NotifyAsync` method. I settled on `object deauthorizationEventReceived` but maybe `string object deauthorizationEventReceived` would be better? Again, I'm open to suggestions.

**Comment by infinite-looper** [comment]
> > On the IDataCompliance.NotifyAsync, the parameter "secret" is not part of the API as far as I can tell. Any reason why you added it?
> 
> The secret is necessary to fulfill the following: `Make a POST request to https://api.zoom.us/oauth/data/compliance and use Basic Auth with Client ID and Secret for authentication.`.
> 
> The developer provided `ClientSecret` when setting up the OAuthConnectionInfo which I could potentially use as the secret but what if the developer is using JWT? The `JwtConnectionInfo` class expects a `ApiSecret` parameter but I have no idea if that's the same "secret" that the data compliance is expecting. That's why I thought it would be simpler to ask the developer to provide the secret as a parameter of the `NotifyAsync` method. Of course, I don't want to ask for information that is not necessary so I'm open to discuss how to improve. Can you think of a better alternative?

I am not a 100% certain this whole notion of Data Compliance applies to JWT applications.  Scopes, installation or permissions on behalf of a user are very specific to OAuth. JWT apps are not published on the market place, so they cannot be uninstalled or deauthorized by a given user. Hence the DC API should not be needed for JWT and you could simply use the OAuthConnectionInfo to authenticate.

> 
> > Also, what a weird API call from Zoom that requires you to send the received object back to them.
> 
> I wholeheartedly agree! I actually struggled to figure out this data would be passed to the `NotifyAsync` method. I settled on `object deauthorizationEventReceived` but maybe `string deauthorizationEventReceived` would be better? Again, I'm open to suggestions.

This kinda loops back to the other discussion we had about providing .NET complex types for the Zoom events. I would suggest using the full definition of the event payload type as an argument but object is fine too.

This is how we've implemented it...

```csharp
public class AppDeauthorizationEventPayload
        {
            [JsonProperty("account_id")]
            public string AccountId { get; set; }

            [JsonProperty("user_data_retention")]
            public bool UserDataRetention { get; set; }

            [JsonProperty("user_id")]
            public string UserId { get; set; }

            public string Signature { get; set; }

            [JsonProperty("deauthorization_time")]
            public DateTime DeauthorizationTime { get; set; }

            [JsonProperty("client_id")]
            public string ClientId { get; set; }
        }

**Comment by Jericho** [comment]
> I am not a 100% certain this whole notion of Data Compliance applies to JWT applications

Good point. Here's what I'll do:
- Throw an exception if the developer is using Jwt and invoking `DataCompliance.NotifyAsync`
- Get the "secret" from OAuthConnection
- Also get the "clientId" from OAuthConnection
- Remove the ClientId and the Secret parameters from the `NotifyAsync` method signature


> This kinda loops back to the other discussion we had about providing .NET complex types for the Zoom events.

I agree. I will leave the type of the `deauthorizationEventReceived` parameter as "object" for the time being but I intend to change it at a later point to match the complex type returned by the Webhook parser I am currently implementing.

**Comment by Jericho** [comment]
Updated beta with changes recently discussed: https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.28.0-datacompliance-r0013
