### ISSUE TITLE
User GetAllAsync "page" parameter

### ISSUE THREAD

**Issue by ninjapiratica** [Jericho/ZoomNet#122]
https://github.com/Jericho/ZoomNet/blob/ef22d52f279c1455edeb5ca5df1dc5f684200f40/Source/ZoomNet/Resources/Users.cs#L58

the [zoom documentation](https://marketplace.zoom.us/docs/api-reference/zoom-api/users/users) says that this parameter should be called "page_number" not just "page"

I don't know what you want to do with this parameter, as they also have the 'next_page_token' as well. This "page_number" is not marked as deprecated yet (as it is marked in other endpoints), so perhaps support both and fix this param name?

**Comment by Jericho** [comment]
Regarding the `page` parameter:
you're right it should be `page_number`. In fact, a quick review of the ZoomNet code base indicates that I made the same typo in 8 places:
- Accounts.GetAllAsync
- CloudRecordings.GetRecordingsForUserAsync
- CloudRecordings.GetRecordingRegistrantsAsync
- Meetings.GetRegistrantsAsync
- Users.GetAllAsync
- Webinars.GetAllAsync
- Webinars.GetRegistrantsAsync

Definitively need to fix that!

Regarding obsolete parameters:
despite the fact that it's not indicated as obsolete in the documentation, my guess is that Zoom intends to make it obsolete at some point. To be consistent with that way I handled this situation in other resources, I suggest marking this method as obsolete and adding an overload of this method that accepts `string pagingToken = null`.

For reference, this is how I handled this situation with the `GetAllAsync` method on the `Meetings` resource:

```csharp
[Obsolete("Zoom is in the process of deprecating the \"page number\" and \"page count\" fields.")]
Task<PaginatedResponse<Meeting>> GetAllAsync(string userId, MeetingListType type = MeetingListType.Scheduled, int recordsPerPage = 30, int page = 1, CancellationToken cancellationToken = default);

Task<PaginatedResponseWithToken<Meeting>> GetAllAsync(string userId, MeetingListType type = MeetingListType.Scheduled, int recordsPerPage = 30, string pagingToken = null, CancellationToken cancellationToken = default);
```

Let me know what you think.

**Comment by ninjapiratica** [comment]
I think that sounds great. Their [announcement](https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements#batch-list-api-changes) definitely seems like it should be marked as deprecated (even if their documentation isn't up-to-date yet).

**Comment by nnanto** [comment]
@Jericho Can you provide an estimate on when 0.27.0 will be available?

**Comment by Jericho** [comment]
There's another open issue that I was planning on completing before releasing 0.27.0 but it's proving more challenging than I initially expected. I will postpone it to another release which will allow me to release 0.27.0 sooner.

**Comment by nnanto** [comment]
@Jericho Seems like the new function was not exposed. I've raised a PR(https://github.com/Jericho/ZoomNet/pull/126#partial-pull-merging) for that. Let me know if that is mergeable.
