### ISSUE TITLE
Missing Obsolete warning

### ISSUE THREAD

**Issue by ninjapiratica** [Jericho/ZoomNet#125]
https://github.com/Jericho/ZoomNet/blob/aeaea240873b9e581411b430b7da1bae684eaf81/Source/ZoomNet/Resources/IUsers.cs#L28

In the last update, this method (on the Users implementation) was marked as obsolete, and a new method was created for the newest way to complete the task. It appears the interface was missed in that change, which means we don't see the new method on the ZoomClient.Users property (since it is just an IUser type).

**Comment by Jericho** [comment]
You're right :astonished: :flushed: 

Will fix it right away.

**Comment by ninjapiratica** [comment]
I really appreciate all the work you put into this project and your prompt responses. It is amazing!
