### ISSUE TITLE
Review GetPropertyValue extension method

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#137]
@vesuvian and I started a discussion in #134 about the need to review the parameters passed to the GetPropertyValue extension methods but I think a separate issue is necessary so we can discuss this change more specifically.

Before we begin the discussion, let me present the current signature of the two overloads to refresh our memory:

```csharp
internal static T GetPropertyValue<T>(this JToken item, string name, T defaultValue = default);
internal static T GetPropertyValue<T>(this JToken item, string name, bool throwIfMissing = true);
```

These signatures are problematic because you can specify that you don't want to throw an exception when a property is missing but you can't specify the default value in that scenario. @vesuvian suggestion was to have a single method that allows you to specify both the default value and whether you want an exception to be thrown when the property is missing.

@vesuvian: did I summarize the situation correctly?

**Comment by vesuvian** [comment]
Spot on. I'll dig up the real example where the defaultValue overload was failing me when I get a chance to loop back.

**Comment by Jericho** [comment]
I'm not a proponent of having a single method allowing you to specify `defaultValue` and `throwIfMissing` for two reasons:
1. the default value is meaningless in the case where you want an exception when the property is missing. I would go even further and say that it's contradictory to indicate you want an exception when property is missing and to specify a default value to be used when property is missing.
2. a lot of code would need to be modified to invoke this new method instead of either one of the previous overloads which could lead to bugs. This is the reason why I was nervous about the change related to this in #134 and ultimately why I wanted to have a separate discussion about this and why I asked @vesuvian to back out the new logic from his PR.

I suggest instead that we have the following two overloads of this method:

- The first overload would allow specifying a default value. In this scenario, it is safe to assume that you don't want an exception to be thrown when the property is missing.
```csharp
internal static T GetPropertyValue<T>(this JToken item, string name, T defaultValue);
```

- The second overload would **NOT** allow specifying a default value. In this scenario, it is safe to assume that you want an exception to be thrown when the property is missing.
```csharp
internal static T GetPropertyValue<T>(this JToken item, string name);
```

Other thoughts:
- Current code that invokes this extension method with a default value would remain unchanged. Therefore no risk of introducing bugs.
- We would need to modify current code that invokes this extension method with `throwIfMissing=true` to simply remove the boolean argument. The underlying behavior would remain unchanged and therefore no risk of introducing bugs
- We would need to modify current code that invokes this extension method with `throwIfMissing=false` to remove the boolean argument and specify the desired default value. This is a scenario where we could potentially introduce bugs.

One more thought:
In the course of investigating this situation I reviewed the current code in the GetPropertyValue overload that accepts a default value which is intended to be returned when the desired property is missing from a JToken, I discovered that it is not working as intended. Here's the current code:

```csharp
internal static JToken GetProperty(this JToken item, string name, bool throwIfMissing = true)
{
    ... omitted for brevity ...
}

internal static T GetPropertyValue<T>(this JToken item, string name, T defaultValue = default)
{
    var property = item.GetProperty(name);
    if (property == null) return defaultValue;
    return property.Value<T>();
}
```

The problem is that `item.GetProperty(name)` is invoked without specifying whether an exception should be thrown in case the property is missing, and the C# compiler uses the `true` default value defined in the GetProperty method signature which means that an exception will be thrown **despite** the fact that a default value is specified. This is the exact opposite of what is intended!!!

This bug needs to be fixed (obviously!!!) and furthermore I will remove the `= true` default value in the GetProperty method signature to force a boolean value to be specified whenever this method is invoked and therefore remove any ambiguity.

**Comment by Jericho** [comment]
One more argument in favor of dropping the `bool throwIfMissing = true` from `GetPropertyValue`:

in the following scenario, will the C# compiler interpret the boolean value as the default value in case the property is missing or will it interpret it as `throwIfMissing = false`?
```csharp
RequireAuthentication = response.GetPropertyValue("meeting_authentication", false),
```

What's worse is that, no matter what the compiler interpretation is, we don't know if it matches the developer's intent.

**Comment by Jericho** [comment]
> * We would need to modify current code that invokes this extension method with `throwIfMissing=true` to simply remove the boolean argument. The underlying behavior would remain unchanged and therefore no risk of introducing bugs

There are 19 instances of `GetPropertyValue` being invoked with `throwIfMissing=true`. Even though it's a moderately significant number of lines of code being changed, I'm still comfortable with this change since the underlying behavior remains unchanged.

> * We would need to modify current code that invokes this extension method with `throwIfMissing=false` to remove the boolean argument and specify the desired default value. This is a scenario where we could potentially introduce bugs.

There is only one instance of `GetPropertyValue` being invoked with `throwIfMissing=false`. So I'm comfortable that the risk of introducing bugs is extremely low.
