### ISSUE TITLE
Zoom Users - Error creating new User with UserCreateType = Auto

### ISSUE THREAD

**Issue by MarteFilho** [Jericho/ZoomNet#139]
The method = CreateAsync(string email, string firstName = null, string lastName = null, UserType type = UserType.Basic, UserCreateType createType = UserCreateType.Normal, CancellationToken cancellationToken = default); 

Has problem when the UserCreateType.Auto is used, because the zoom api require the password in the request for this case.

 - This action is provided for the enterprise customer who has a managed domain. This feature is disabled by default because of the security risk involved in creating a user who does not belong to your domain.
 - User password. Only used for the “autoCreate” function. The password has to have a minimum of 8 characters and maximum of 32 characters. By default (basic requirement), password must have at least one letter (a, b, c…), at least one number (1, 2, 3…) and include both uppercase and lowercase letters. It should not contain only one identical character repeatedly (‘11111111’ or ‘aaaaaaaa’) and it cannot contain consecutive characters (‘12345678’ or ‘abcdefgh’).

The error: Error Code: 300
Invalid parameter: password

Solution: create new parameter in this method, called password and password is optional.

**Comment by Jericho** [comment]
You're right. Looks like I missed the password parameter.
