### ISSUE TITLE
Json parsing errors using the `GetAllMeetingParticipantsQosAsync` api

### ISSUE THREAD

**Issue by ZaL133** [Jericho/ZoomNet#153]
There are 2 incorrect Json Property names on the `DashboardParticipantQos` model. These are causing parsing errors 

The 2 properties are 

`AudioOutput` (labeled as "audio_input")
`VideoDeviceToCrc` (labeled as "audio_device_to_crc")

**Comment by Jericho** [comment]
Thank you for reporting this issue. I will review and merge your PR and get a release published shortly.

**Comment by ZaL133** [comment]
Amazing! Thanks!!
