### ISSUE TITLE
ParticipantDevice Enum

### ISSUE THREAD

**Issue by birdbm** [Jericho/ZoomNet#168]
Good Morning,

While attempting to process more webinars today I ran across another enumeration issue:

![image](https://user-images.githubusercontent.com/97680941/152026214-737d6df3-ec08-4bfd-bd68-077110b51e4c.png)

This causes GetWebinarParticipantsAsync to fail.

**Comment by birdbm** [comment]
As a small update, I wrapped the call in a try/catch and looped through all other webinars and didn't see any other issues related to that endpoint.

**Comment by Jericho** [comment]
I double checked the documentation and they don't mentioned "Unknown" as a possible device, but that's easy for me to add it to ZoomNet.

What's more intriguing is the fact that, if I understand your scenario correctly, a participant can use more than one device (in the example you presented, the participant used "Unknown" and "Phone", separated by the "+" sign). I need to think about how I'm going to model this in ZoomNet and how I'm going to parse this string into an enum.

**Comment by Jericho** [comment]
@birdbm Can you share the JSON you get from SendGrid? That would help me write unit tests to ensure we properly parse the "device".

**Comment by birdbm** [comment]
I'm not sure what SendGrid is, but I have Postman set up and can easily provide the JSON response for that one.  
 "device": "Unknown + Phone"

**Comment by Jericho** [comment]
I meant "Zoom", sorry for the confusion (SendGrid is related to another project I maintain). 

Do you have a sense for what this value means? My best guess is that it means the participant joined a webinar with an unknown device (like a computer, for example) for the video part of a webinar and also used a phone to join the audio part. Does that make sense?

**Comment by birdbm** [comment]
What you said makes sense, but to be honest I'm really not sure exactly what it means.  The integration we are building is actually for one of our customers so I'm not familiar enough with the underlying data to be able to confirm that suspicion.  I'm curious about whether or not there are other combinations that could be sent if that were the case though.

**Comment by Jericho** [comment]
Published a beta to my MyGet feed: https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.39.0-multiple-devices0018

What changed:
- the `Device` property on the `DashboardParticipant` class is an array in order to be able to accommodate multiple devices 
- the `Device` property has been renamed to `Devices` to make it clear that it can contain multiple devices

**Comment by birdbm** [comment]
@Jericho that actually broke the strictly 'Unknown' response.  

![image](https://user-images.githubusercontent.com/97680941/152446237-eb915c7b-d910-41aa-815f-fb56b57e8142.png)

**Comment by Jericho** [comment]
New beta to parse single devices as well as multiple devices: https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.39.0-multiple-devices0020

By the way, I noticed that the sample in the documentation uses a device called "WIN" which is not a valid value as far as I understand the docs:

![image](https://user-images.githubusercontent.com/112710/152452141-f09af95f-7303-477d-8166-2b49d18cb403.png)

I'm hoping it's just a typo and "Windows" is the intended sample device.

**Comment by birdbm** [comment]
@Jericho I'm no longer seeing errors from that endpoint.  Thank you so much for the quick turnaround on these!

**Comment by Jericho** [comment]
Publishing 0.39.0 to NuGet as we speak. Should be available within the next 30 minutes or so.
