### ISSUE TITLE
Access token is expired JWT

### ISSUE THREAD

**Issue by merof-code** [Jericho/ZoomNet#193]
I had a program that was working perfectly, and then it just stopped.
I'm using JWT, like in the readme.
I think that it, for some reason stopped refreshing the token.

So the problem is, I have no idea how to fix this.

I tried using older version of the package, made a new project to check everything. So i really don't know why.

according to the log it just takes the zero unix time. really strange
Here is the log:
```
02:20:31 fail: ZoomDownloader.Program[0]
 REQUEST:
   GET https://api.zoom.us/v2/users/me
   Accept: application/json, text/json, application/xml, text/xml, application/x-www-form-urlencoded
   Authorization: ...redacted for security reasons...
   ZoomNet-Diagnostic-Id: 78f93fde514648ff9a90e54e44eb1e74
   Content-Length: 0
  RESPONSE:
   HTTP/1.1 401
   Date: Wed, 16 Mar 2022 13:24:38 GMT
   Transfer-Encoding: chunked
   Connection: keep-alive
   x-zm-trackingid: v=2.0;clid=us02;rid=WEB_61ebc1c8aa27dce6fa80823a12c3729a
   X-Content-Type-Options: nosniff
   Cache-Control: no-store, no-transform, must-revalidate, no-cache
   Pragma: no-cache
   Set-Cookie: zm_aid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, zm_haid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, zm_tmaid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, zm_htmaid=""; Domain=.zoom.us; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; Secure; HttpOnly, cred=16F95E0B8D8E49B63FDD431DC9B81666; Path=/; Secure; HttpOnly, TS01d0dc3f=01377c1b7355d2cbccf15dae4d92a450614f8dd9423786e829524eff90c0390bc637a1c64b9d14b34b8d95afc2ef63321d282ff4f9; Path=/; Secure; HttpOnly; SameSite=Strict;, TS01a42040=01377c1b7355d2cbccf15dae4d92a450614f8dd9423786e829524eff90c0390bc637a1c64b9d14b34b8d95afc2ef63321d282ff4f9; path=/; domain=.zoom.us
   x-zm-zoneid: VA
   Content-Type: application/json; charset=UTF-8
   Expires: Thu, 01 Jan 1970 00:00:00 GMT
  {{"code":124,"message":"Access token is expired."}}
  DIAGNOSTIC:
   The request took 304 milliseconds
```

**Comment by merof-code** [comment]
Thank you for your reply!

It magically works again. I didnt change a single char. I have no idea why it works now.
Big thanks! 

1) any request is rejected with `{{"code":124,"message":"Access token is expired."}}`
2)No  don't see that it refreshes the token, which is very strange.

> I'm afraid I don't understand what you are trying to say. Can you please explain?

I mean 

> Expires: Thu, 01 Jan 1970 00:00:00 GMT

which is the expiration date set by default in the ZoomNet

I checked in postman JWT key that zoom marketplace provides, it works. And double checked the _apiKey and _apiSecret

So I now cant dig in deeper. Thank you anyway.

**Comment by Jericho** [comment]
> which is the expiration date set by default in the ZoomNet

To be clear: this header is NOT set by ZoomNet and it has nothing to do with the authentication process. The header is set by the web server to let clients know how long they can cache the payload. More information available [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Expires). In the case, Zoom's web server set the value of this header to a date in the past to indicate that the content should not be cached.

**Comment by merof-code** [comment]
oh thanks, didn't know that.
