### ISSUE TITLE
New resource: Contacts

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#21]

**Comment by Jericho** [comment]
When I try to retrieve the contacts for a given user, I get the following error: ` Invalid access token, does not contain scopes: [chat_contact:read].` which typically indicates that my OAuth app was not granted the necessary permission. 

However, in this case, the permission mentioned in the error message doesn't seem to exist neither under "chat" nor under "contacts":

![image](https://user-images.githubusercontent.com/112710/104370169-75c82c80-54ec-11eb-9166-434a803f25ac.png)

![image](https://user-images.githubusercontent.com/112710/104369847-0f430e80-54ec-11eb-8ed3-096b892a2639.png)

**Comment by Jakebluhm** [comment]
I am trying to get the presence_status from the current user and getting it though /contacts seems to be the only way to accomplish this using the API. Any chance this will be operational soon? Or is it already available for use?

Side note, you are a legend for making this. Zoom's documentation is a real struggle.

**Comment by Jericho** [comment]
WAIT A SECOND! I just noticed something in the documentation:

![image](https://user-images.githubusercontent.com/112710/117682291-e58bb280-b180-11eb-8feb-0aa8c6992bbb.png)

It so happens that the app I created for testing purposes is an "Account" OAuth app, not a "User" OAuth app. That probably explains why I'm being denied access to this functionality. Let me create a user app real quick and see if it resolves this issue.

**Comment by Jericho** [comment]
That was it. I created a user app, installed it in my user account and I am now able to to search for contacts. This is great news, it will allow me to make progress. 

My next challenge is to figure out how to add contacts so that so that a few records are returned when searching for contacts...
