### ISSUE TITLE
meeting.participant_joined event join_time property

### ISSUE THREAD

**Issue by chiarapivetta** [Jericho/ZoomNet#229]
I just found another inconsistency with the meeting.participant_joined event in the Zoom documentation. It seems like they changed the name of the **date_time** property to **join_time**. If we look at the sample, though, it's still indicated as date_time!

![image](https://user-images.githubusercontent.com/38748810/179181735-ef959a31-7169-46dd-be7a-10eda5cad88d.png)

![image](https://user-images.githubusercontent.com/38748810/179181929-fd4bd30c-6f21-4d4c-bacc-827c2d3bc625.png)

The events I'm receiving have join_time, so I get an exception:
```
System.ArgumentException: Unable to find 'object/participant/date_time' (Parameter 'name')
    at ZoomNet.Internal.GetProperty(JsonElement element, String name, Boolean throwIfMissing)
    at ZoomNet.Internal.GetPropertyValue[T](JsonElement element, String name, T defaultValue, Boolean throwIfMissing)
    at ZoomNet.Internal.GetPropertyValue[T](JsonElement element, String name)
```

**Comment by Jericho** [comment]
This is distressing and frustrating, we can't trust the documentation and we can't get help when we point out these discrepancies in their documentation.

So now, I need to figure out a way to handle *EITHER* `join_time` or `date_time`???!?!?!?!

**Comment by chiarapivetta** [comment]
I'm pretty sure they just forgot to update the samples, since I'm getting JSONs with join_time from Zoom in these days.

**Comment by Jericho** [comment]
You're probably right: they probably switched to `join_time`, so that's the only name we will support going forward.
