### ISSUE TITLE
Getting past meeting API reveals Meeting class instead of PastMeeting

### ISSUE THREAD

**Issue by pzelenko** [Jericho/ZoomNet#231]
Hi Jericho,
I noticed that getting past meeting API (GetAsync() API) returns ref of Meeting class instead of PastMeeting class (defined in ZoomNet/Source/ZoomNet/Models/PastMeeting.cs file).

public interface IPastMeetings
	{

		/// Retrieve the details of a meeting that occured in the past.
		/// <param name="uuid">The meeting UUID.</param>
		/// <param name="cancellationToken">The cancellation token.</param>
		/// <returns>
		/// The <see cref="Meeting" />.
		/// </returns>
		Task<Meeting> GetAsync(string uuid, CancellationToken cancellationToken = default)
}

While Zoom REST API past_meetings returns information about past meeting including actual start/end time of the finished meeting. Here is the sample result of REST API call:
    "uuid": "*****",
    "id": *****,
    "host_id": "**********",
    "type": 2,
    "topic": "Test meeting 15 min",
    "user_name": "*******user_name",
    "user_email": "******user_mail",
    "start_time": "2022-07-22T15:26:17Z",
    "end_time": "2022-07-22T15:29:50Z",
    "duration": 4,
    "total_minutes": 4,
    "participants_count": 1,
    "dept": "",
    "source": "Zoom"

What is the reason you are not returning PastMeeting class, which has all the attributes above?
I could not find another way of getting past meeting actual start/end time using ZoomNet

Thanks in advance

**Comment by Jericho** [comment]
My best guess is that this is a copy/paste mistake on my part. The return type of this method definitely should be `PastMeeting`.

**Comment by pzelenko** [comment]
Thanks a lot for a quick response. What do you think, when can we expect a release with this fix?

**Comment by Jericho** [comment]
You reported this issue barely an hour ago and already you expect a fix and a release !!! :stuck_out_tongue_winking_eye:

Joking aside, I should be able to publish a release in the next day or two.

**Comment by pzelenko** [comment]
Great! Thanks a lot for your great support. I am actively using your package, that's the reason for such a rush :) 
BTW, does the package support Zoom Phone API ?

**Comment by Jericho** [comment]
> does the package support Zoom Phone API ?

There are several endpoints in Zoom's API that I haven't worked on, mostly due to the fact that I don't have the necessary permissions to access them. I applied for membership in Zoom's partner program (which, I assume, would grant me access to the entirety of the API) but never heard back. I also [asked for assistance](https://github.com/Jericho/ZoomNet/issues/160), but so far no progress has been made.

**Comment by pzelenko** [comment]
Well done, thank you! It is working!
