### ISSUE TITLE
Users.GetCurrentAsync throws error if user has a phone number but no label Bug (part 2)

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#235]
The fix for #234 solved the problem of not being able to omit the phone number label when creating a new phone number, but it did not solve the problem that @michael-aj-kennedy was reporting which is that ZoomNet throws an exception when retrieving a user who has a phone number without a label. Sorry Michael.

The root of this problem is that Zoom returns a value (albeit a blank one) to mean that this property does not contain a value. It's a little unusual on Zoom's part but not unprecedented. For example, when signing up for a webinar/meeting, registrants can skip some of the optional questions such as "Purchasing Time Frame", "Number of employees", etc. and when you subsequently retrieve the registrants, the answer to each skipped question will contain a blank value which signifies that the registrant did not provide an answer. The way I worked around this situation was by adding a "unknown" value in the `PurchasingTimeFrame` enum (I did the same for `NumberOfEmployees` and a few other enums as well):

```csharp
public enum PurchasingTimeFrame
{
    /// <summary>Unknown</summary>
    [EnumMember(Value = "")]
    Unknown,

    ... snip ...
}
```

@michael-aj-kennedy: I could resolve the problem you are reporting by adding a "unspecified" value to the `PhoneType` enum like so:

```csharp
public enum PhoneType
{
    /// <summary>Unspecified</summary>
    [EnumMember(Value = "")]
    Unspecified,

    /// <summary>Mobile.</summary>
    [EnumMember(Value = "Mobile")]
    Mobile,

    ... snip ...
}
```

Your code would have to interpret this value to mean that a given phone number does not have a label. Does this solution sounds reasonable?

**Comment by michael-aj-kennedy** [comment]
@Jericho That sounds like the best approach to me.  I nearly created a PR this morning that did just that but got side-tracked trying to coax Json into treating the empty string as a null!

**Comment by Jericho** [comment]
Perfect, thanks for confirming. I'll publish a fix in the next hour or so. Sorry again for not properly addressing the problem you reported yesterday.

**Comment by michael-aj-kennedy** [comment]
Thanks for this.  The delay isn't a problem - client has a workaround so there's no rush.

**Comment by michael-aj-kennedy** [comment]
Works perfectly, thank you again :)
