### ISSUE TITLE
The IJsonTypeInfoResolver returned a JsonTypeInfo instance whose JsonSerializerOptions setting does not match the provided argument

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#248]
As I have learned [here](https://github.com/Jericho/StrongGrid/issues/476), cloning Json serialization options is problematic when library targets .net6 and is being used in a .net7 application.

The culprit is this line in `ZoomNetJsonConverter`:
```csharp
var clonedOptions = new JsonSerializerOptions(options);
clonedOptions.Converters.Add((JsonConverter)Activator.CreateInstance(propertyConverterAttribute.ConverterType));
```

it can be replaced with:
```csharp
var customOptions = new JsonSerializerOptions()
{
	Converters = { (JsonConverter)Activator.CreateInstance(propertyConverterAttribute.ConverterType) }
};
```

**Comment by tmoreland-r7** [comment]
nevermind, I had forgotten to push an updated dependency (updated to support net7.0) so it was still using the older net6.0 build which I'm assuming is the cause, leaving this here in case anyone else finds this via bing/google/whatever
