### ISSUE TITLE
Would be good if there was support for decrypting ZoomApps AppContext

### ISSUE THREAD

**Issue by cdmdotnet** [Jericho/ZoomNet#254]
see https://marketplace.zoom.us/docs/zoom-apps/zoomappcontext/

**Comment by Jericho** [comment]
In what context is this "AppContext" relevant/useful? My understanding is that this context is relevant only when you code is running in an app in a user's Zoom app. Does that sound about right?

My first inclination is to say that this doesn't really fit with ZoomNet's goal to simplify how developers connect and interact with the Zoom REST API.
