### ISSUE TITLE
Allow for creating a meeting using a default password

### ISSUE THREAD

**Issue by mxswd** [Jericho/ZoomNet#281]
When creating a meeting there are 3 security options, and you must pick at least one.

If you use the API to create a meeting these security options don't match the API 1-to-1, but rather you need to combine certain options to trick zoom into working the way you want.

It seems if you want:

1. To allow participants to join before the host
2. Disable waiting room
3. Don't require authentication

<img width="685" alt="Screenshot 2023-04-08 at 11 32 02 AM" src="https://user-images.githubusercontent.com/136101/230697519-0cc9c07b-6de9-4208-afbb-5523eed950f2.png">

You need to send a request with:

1. `join_before_host` set to true.
2. `jbh_time` set to an integer.
3. `waiting_room` set to false.
4. A password set.

Admin's have an array of options to configure meeting password strength so the API provides a convenient `default_password` option so you don't need to lookup the account password options and generate one that matches those rules yourself.
 
<img width="623" alt="Screenshot 2023-04-08 at 11 37 11 AM" src="https://user-images.githubusercontent.com/136101/230697673-5c9be837-32bc-4199-a159-2ce1355ba213.png">

I'm basing this off the light amount of documentation on:

https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate

And significant testing on my side.

**Comment by Jericho** [comment]
Makes a lot of sense to enable developers to request the password to be auto-generated.

Also, I'm intrigued by this comment you made: 
> When creating a meeting there are 3 security options, and you must pick at least one.

What happens if a developer attempts to create a meeting but does not pick any of the options? Do they get a clear error message from Zoom? If not, is this something we should validate in ZoomNet? FYI: [my attitude regarding validation](https://github.com/Jericho/ZoomNet/discussions/86) has been to avoid it as much as possible because who knows if/when the validation rules in the Zoom API change and I would hate to enforce some validation rule that makes sense today but may or may not still be valid in the future. Having said that, I'm willing to make exceptions if there are situations that cause confusion, unclear error messages, unexpected outcome, etc.

**Comment by mxswd** [comment]
I did some testing it seems if you try to pick none of the options it will force the waiting room option. For example if you send this request:

```
await zoomClient.Meetings.CreateScheduledMeetingAsync(userId, calendarEvent.Summary, calendarEvent.Description, calendarEvent.DtStart.ToTimeZone("AUS Eastern Standard Time").Value, calendarEvent.Duration.Minutes, ZoomNet.Models.TimeZones.Australia_Sydney, settings: new ZoomNet.Models.MeetingSettings {
    JoinBeforeHost = true,
    WaitingRoom = false,
    ApprovalType = ZoomNet.Models.ApprovalType.None,
    UsePmi = false
});
```

It ignores the `WaitingRoom = false` and you get a meeting with waiting room enabled. And if you add the `default_password` flag to this API call you get a meeting room with WaitingRoom disabled and passcode enabled.

**Comment by LucasMetal** [comment]
Just passing by.... I noticed I have recently read something about this topic here:
https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0059862

In the first paragraphs it explains the behavior that @mxswd mentions.

Hope this helps ;)

**Comment by Jericho** [comment]
Thanks for the link. Sadly the original contributor never completed the PR.

@LucasMetal would this functionality be useful to you?

**Comment by LucasMetal** [comment]
No, I don't need it (at least for now). 
I was checking something else, and just thought the link could be useful.

Keep up the good work!!
Thanks!

**Comment by Jericho** [comment]
Note to those interested in this new parameter: it appears that a custom password you specify when creating a meeting takes precedence. This means that setting the new `generatePassword` to true is not sufficient to generate a password, you must also set the `password` parameter to `null`.

Also note that when you set this new parameter to true,  Zoom will **EITHER** generate a random password **OR** use the default password configured in your user's security settings. It's not 100% clear to me what determines which of the two actions is taken.

**Comment by mxswd** [comment]
Awesome, thanks a lot for making the change. It will help a lot.

**Comment by Jericho** [comment]
You're welcome. I raised #374 to warn developers about the breaking changes and guide them to resolution. Hopefully my instructions are clear.
