### ISSUE TITLE
Add support for webinar participants report

### ISSUE THREAD

**Issue by GiampaoloGabba** [Jericho/ZoomNet#284]
Currently we can get the participants report only for meeting.

To get them for webinars is very similar:
https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/reportWebinarParticipants

> GET /report/webinars/{webinarId}/participants
> Use this API to get a detailed report on each webinar attendee. You can get webinar participant reports for the last 6 months.

**Comment by Jericho** [comment]
This is a very nice improvement. I do not have access to Webinars so I'll trust that you tested. The fact that you included integration tests is greatly appreciated!
