### ISSUE TITLE
Webinar Id deserialization issue

### ISSUE THREAD

**Issue by GiampaoloGabba** [Jericho/ZoomNet#285]
I'm trying to deserialize a webinar.ended response and i encountered the same deserialization issue you had with the meeting id that sometimes is passed as number and sometimes as string (#228).  The `webinar.id` property has the same issue.

`System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.id `

I alredy have a fix and the relative unit-test, doing a PR right now.

**Comment by Jericho** [comment]
Excellent, thanks for reporting this issue and for submitting the PR.
