### ISSUE TITLE
Add more properties to Participant data model

### ISSUE THREAD

**Issue by ivan-pavlik** [Jericho/ZoomNet#287]
Currently Participant data model has three properties: Uuid, Email, DisplayName.

Please add the following properties:
JoinTime ("join_time" json property), LeaveTime ("leave_time"), Duration ("duration").

This is required to be able to fully use result of IPastMeetings GetParticipantsAsync method and check when each participant joined and left the meeting.

**Comment by Jericho** [comment]
In addition to the three properties you mentioned, there are also a few more missing properties such as `Status` and `Failover`.

**Comment by Jericho** [comment]
@ivan-pavlik  : I published a beta package to my MyGet feed to allow you to test this enhancement. Please let me know if it works as expected: https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.62.0-gh-287-0007

@GiampaoloGabba, @dombrovsky, @pzelenko, @birdbm : Zoom's API returns additional information when retrieving meeting participants and I modified the `Participant` class accordingly. These changes had the side effect of forcing me to make changes  to other related classes such as `ReportParticipant` and allowed me to eliminate redundant classes such as `ReportMeetingParticipant` and `ReportWebinarPArticipant`. All this to say that my changes touched areas of the library that you guys have contributed to in the past. If you have a chance, please take the beta package for a spin and let me know if I broke anything.

**Comment by dombrovsky** [comment]
@Jericho thanks for bringing this up.
I briefly checked `ZoomNet.IntegrationTests.Tests.Reports` and it seems to have all values set correctly in `ReportParticipant`.
I haven't find the source code for this change yet, which may be helpful to see what else potentially worth checking.

**Comment by Jericho** [comment]
@dombrovsky Thanks for confirming. The changes haven't been merged yet. In the mean time, you can find them [here](https://github.com/Jericho/ZoomNet/tree/feature/gh_287)

**Comment by ivan-pavlik** [comment]
> @ivan-pavlik : I published a beta package to my MyGet feed to allow you to test this enhancement. Please let me know if it works as expected: https://www.myget.org/feed/jericho/package/nuget/ZoomNet/0.62.0-gh-287-0007
> 

Thank you for the prompt response! -)
I have tried the new package and I can confirm that new properties are available in Participant model and values are the same as I get via Zoom API from Postman.

**Comment by Jericho** [comment]
@ivan-pavlik Thank you for confirming that it's working as you expected. I'll give the other contributors some time to verify that I didn't break anything since the `Participant` class is used on other areas as well (such as dashboard, reports, pas meetings, past webinars, etc.) before publishing a new package.

**Comment by pzelenko** [comment]
@Jericho I did a quick verification of the new package on my side, and it seems got correctly filled data for the participants.

**Comment by Jericho** [comment]
@pzelenko Thank you for confirming.
