### ISSUE TITLE
Add RecordingCompleteEvent

### ISSUE THREAD

**Issue by synesthesia** [Jericho/ZoomNet#296]
Hi @Jericho 

I've got to implement this for myself anyway as am building a function to extract zoom recordings for our business and archive them in other storage.

Would you be interested in a PR with just the one message in it? (of course including all the parsing and tests)

Julian

**Comment by Jericho** [comment]
Absolutely! I definitely welcome contributions.

**Comment by synesthesia** [comment]
OK great!

My priority is to get it running in my app (where I include your code as source as I need to make a couple of minor changes elsewhere), but when I have done that I should be able to cherry pick across into a PR branch based off `develop`

Have tried to copy your code style exactly so hopefully will be an easy review for you.

**Comment by synesthesia** [comment]
However obviously something not right in my set-up, when I run Cake locally just in the ZoomNet code getting lots of StyleCop errors, which of course in Release mode are breaking the build.... Didn't think I had touched anything around that config so will try a clean clone of my fork.
