### ISSUE TITLE
Add `Type` to Recoding model class

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#298]

**Comment by synesthesia** [comment]
From thje documentation for API event for [`recording.completed`](https://developers.zoom.us/docs/api/rest/reference/zoom-api/events/#operation/recording.completed):

`type` is integer with following possible values:

If the recording is of a meeting:

1 — Instant meeting.
2 — Scheduled meeting.
3 — A recurring meeting with no fixed time.
4 — A meeting created via PMI (Personal Meeting ID).
7 — A [Personal Audio Conference](https://support.zoom.us/hc/en-us/articles/204517069-Getting-Started-with-Personal-Audio-Conference) (PAC).
8 - Recurring meeting with a fixed time.


If the recording is of a webinar:

5 — A webinar.
6 — A recurring webinar without a fixed time.
9 — A recurring webinar with a fixed time.

If the recording is not from a meeting or webinar:

99 — A recording uploaded via the [Recordings](https://zoom.us/recording) interface on the Zoom Web Portal.

**Comment by Jericho** [comment]
As [discussed](https://github.com/Jericho/ZoomNet/pull/297/commits/a1d63218a18aa9837b0e341f4a0aa8c6d421f982#r1239413851) in a PR recently submitted by @synesthesia, ZoomNet already contains an enum called RecordingType which is used to indicate whether a file is saved locally or in the cloud. Therefore it should have been name something like "RecordingSaveLocation".

**Comment by Jericho** [comment]
More specifically, the existing type is used when configuring meeting (or webinar) settings. When you are configuring these settings, you have the ability to indicate whether the meeting is automatically recorded and if so, where the recording is saved (either in the cloud or local).

Therefore I think "RecordingAutoSaveType" is a better name. Naming is hard... :pensive: 
Suggestions are welcome!

**Comment by Jericho** [comment]
How about just `AutoRecordingType`?
