### ISSUE TITLE
Add `FileExtension` to RecordingFile model class

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#299]

**Comment by synesthesia** [comment]
I'll clean this up in the PR I'm doing

**Comment by Jericho** [comment]
Thanks for adding this property to the Model class.  I want to change the type to enum though since, according to the [documentation](https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/recordingGet), there's a finite number of possible extensions: 

> The file extension type of the recording file. Allowed: MP4┃M4A┃TXT┃VTT┃CSV┃JSON┃JPG

For some reason this is not mentioned in the documentation for the webhook event you were working on. I wonder why the inconsistency?
