### ISSUE TITLE
Invalid conditional used when checking if there are total records when retrieving call logs

### ISSUE THREAD

**Issue by joshrogers-pg** [Jericho/ZoomNet#307]
When retrieving call logs against a user who has zero records an exception is thrown:
`Exception: The response does not contain a field called 'call_logs' (Parameter 'propertyName')`

This appears to be because there is a bug in the retrieval logic that is looking at page size rather than total records to determine whether to throw the exception or not.

https://github.com/Jericho/ZoomNet/blob/3c3f0d40dc4372c861079eb72d3eeaeafc4a430b/Source/ZoomNet/Extensions/Internal.cs#L958-L989

Line #974 is checking for page size but the comments suggest it should be total records and looking at the payload that is if failing on, it appears checking for total_records > 0 would be the correct conditional.

```
{
  "next_page_token": "",
  "page_size": 100,
  "total_records": 0,
  "from": "2023-07-05",
  "to": "2023-07-12"
}
```

**Comment by Jericho** [comment]
You're right. Thanks for reporting this issue.

I'll write unit tests to highlight the faulty behavior you discovered and it will also allow us to validate that your PR solves this problem.
