### ISSUE TITLE
Group integration tests into "suites"

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#313]
Currently, the integration project runs all API tests which, until recently, was fine but it is now problematic because #312 is adding ChatBot tests which require different credentials and these credentials do not seem to be allowed to invoke many of the API endpoints (such as, for example, retrieving info about the current user, getting the list of existing roles, etc.). This means that we need to be able to group our integration tests into logical groups (which I call suites) and allow the developer running the tests to specify which suite he wants to run.

I can think of three suites: API, ChatBot and WebSockets.

There is a line in TestRunner.cs where developer would be able to specify which of the three he wants to run:
![image](https://github.com/Jericho/ZoomNet/assets/112710/ea31e5d6-19fd-46cf-882f-3eb0de886283)

The integration test project would contain a "suite" class for each of the three scenarios:
![image](https://github.com/Jericho/ZoomNet/assets/112710/1497d828-1f4d-44a0-8885-63b769e5367f)

And each of these three classes would define the list of individual tests that are grouped toghether. Something like this:
![image](https://github.com/Jericho/ZoomNet/assets/112710/4005f712-b605-499c-bfbe-64492761bde7)

**Comment by theit8514** [comment]
As an aside, I think that it would be great to have the different flows of the OAuth separated out in the OAuth enum. This way you could have the environment variables set in the background without having to juggle them.

`OAuthAuthorizationCode` -> Gets authorization code and sets refresh token.
`OAuthRefreshToken` -> Gets and sets refresh token and access token.
`OAuthClientCredentials` -> Gets and sets access token. For cleanliness, it should use a different access token environment variable so they don't cross contaminate.
`OAuthServerToServer` -> Gets the account id and access token and sets access token. Same as above.

**Comment by Jericho** [comment]
>  it would be great to have the different flows of the OAuth separated out in the OAuth enum

I like this idea.

>  For cleanliness, it should use a different access token environment variable so they don't cross contaminate.

Totally agree. In fact, I bumped into this problem when running your ChatBot integration tests.

**Comment by Jericho** [comment]
Something along these lines:

```csharp
private enum TestType
{
	Api,
	WebSockets,
	ChatBot,
}

private enum ConnectionType
{
	Jwt, // Zoom disabled the ability to create new JWT apps on June 1, 2023. The projected end-of-life for JWT apps is September 1, 2023. 
	OAuthAuthorizationCode, // Gets authorization code and sets refresh token.
	OAuthRefreshToken,      // Gets and sets refresh token and access token.
	OAuthClientCredentials, // Gets and sets access token. For cleanliness, it should use a different access token environment variable so they don't cross contaminate.
	OAuthServerToServer,    // Gets the account id and access token and sets access token. Same as above.
}
```

**Comment by Jericho** [comment]
@theit8514 I have completed this enhancement in branch `feature/integration_tests_suites`. Let me know if you have a minute to sanity check because I merge it. In particular, look at the new readme file in the integration tests project where I explain how to configure the tests and also included a convenient chart listing all the necessary environment variables depending on the test suite and authentication flow you select.

**Comment by Jericho** [comment]
I'm going to go ahead and merge this branch.
