### ISSUE TITLE
Meetingdevice enum is not getting deserialized

### ISSUE THREAD

**Issue by jinthakur** [Jericho/ZoomNet#314]

**Comment by Jericho** [comment]
I would love to help but you are not giving me much details. How would I go about reproducing this problem? Are you getting an error message? Do you have a stack trace you can share? Can you share the JSON payload you receive from Zoom? Maybe a code snippet to reproduce? Which ZoomNet method were you invoking when you experienced the problem?

**Comment by Jericho** [comment]
@jinthakur Let me know if you intend to provide the addition information necessary to investigate this situation. Otherwise I'll close this issue.

**Comment by jinthakur** [comment]
I fixed the issue. It is a data issue. Thanks for your help.
