### ISSUE TITLE
ZoomNet library always refreshes access tokens despite of the Token Expiration time

### ISSUE THREAD

**Issue by aperepadja** [Jericho/ZoomNet#315]
ZoomNet library always refreshes access tokens despite the Token Expiration time.

It is a violation of Zoom validation rules to go Prod.
https://developers.zoom.us/docs/distribute/app-submission/submission-checklist/#11-optimize-app-authentication-and-refresh-flows

ZoomNet needs to have the method to get OAuthConnectionInfo with the current valid access token. 
or updated version of OAuthConnectionInfo.WithRefreshToken which will track the expiration time of the access token & do not refresh it each call time.

**Comment by Jericho** [comment]
There is already an overload of the `WithRefreshToken` method that allows you to specify your access token as you can see here: https://github.com/Jericho/ZoomNet/blob/develop/Source/ZoomNet/OAuthConnectionInfo.cs#L362

**Comment by Jericho** [comment]
Closing this issue as we haven't heard back. I am assuming the link I provided was the information OP was seeking.
