### ISSUE TITLE
Add get account call logs feature

### ISSUE THREAD

**Issue by joshrogers-pg** [Jericho/ZoomNet#323]
ZoomNet already provides the feature to retrieve the call logs for an individual user. It would also be beneficial to include the feature to retrieve an entire accounts call logs.

The API endpoint is here: https://developers.zoom.us/docs/api/rest/reference/phone/ma/#operation/accountCallLogs

Note: I hope to address this with a PR soon, but wanted to get it on your radar or someone else's if they can tackle sooner

Thank you.

**Comment by Jericho** [comment]
I'll be glad to accept your PR. In the mean time, have assigned this issue to you so it's clear that you are working on this new feature.

**Comment by f-rakete** [comment]
@joshrogers-pg hey there, I was looking for the same feature and it brought me here - Before I start on implementing this - did you already start on it? Happy to collab if you want, but I just don't want to repeat your work if its already in process.

**Comment by Jericho** [comment]
@dyzenment you should definitely submit a PR with your work.
