### ISSUE TITLE
ZoomRoom not present in enum

### ISSUE THREAD

**Issue by HS-Dave** [Jericho/ZoomNet#324]
Hi, we are getting a new exception in an existing mature implementation when users are using a Zoom Room device to host their meetings, specifically:  

There is no value in the ParticipantDevice enum that corresponds to 'Zoom Rooms'

Indeed that value is not present in that enum within zoomnet. It may be something they have recently added or modified - is there any plan to add this soon?

 I see in the past there was a similar bug when they decided to return "Web" - if they are going to keep modifying this maybe we also need an Unknown option at the end of the enum to fall back on? :)

**Comment by Jericho** [comment]
Thanks for reporting this issue. 

You don't mention it, but I'm guessing you get this error when trying to retrieve the list of people who attended a given meeting or webinar by invoking `Dashboard.GetMeetingParticipantsAsync` or `Dashboard.GetWebinarParticipantsAsync`, am I right?

I double checked Zoom's documentation for the "List meeting participants" and the "Get webinar participants" endpoints and neither have been updated to reflect additional possible values such "Web" that we discovered about a year ago or the value you discovered today. 

Having said that, I'll be happy to modify the enum to add the new value you discovered today but I need more info from you: specifically, I need a sample of the JSON returned from the Zoom API that shows the participant device node and/or the actual error message. This will allow me to get the exact spelling of this new enum value. In the title of this issue, you spelled it `ZoomRoom` (singular, all in one word) but in your original comment you spelled it `Zoom Rooms` (plural, with a space between the two words). I don't want to be guessing what the correct spelling is. So, please provide either the JSON or the actual error message or, even better, provide both.

**Comment by Iram1995** [comment]
Hey Jericho ,
I am getting following exception while calling invoking Dashboard.GetMeetingParticipantsAsync or Dashboard.GetWebinarParticipantsAsync.
![Zoom_exception](https://github.com/Jericho/ZoomNet/assets/52947627/4c1dce31-f436-4d1c-a95a-413b10a2afc0)

**Comment by Jericho** [comment]
Thank you for confirming. I'll get this value added to the enum.

**Comment by Iram1995** [comment]
Great, It worked
Thank you.
