### ISSUE TITLE
Add ability to retrieve a Zoom Phone user's profile

### ISSUE THREAD

**Issue by joshrogers-pg** [Jericho/ZoomNet#330]
We are in need of retrieving the profile for a Zoom Phone user.  It turns out this profile differs based on which API you're calling, e.g. the meeting API returns different values for phone numbers and such.

This API endpoint can be found here:
https://developers.zoom.us/docs/api/rest/reference/phone/methods/#operation/phoneUser

Note: I'll be submitting a PR very shortly for this feature.

Thank you.

**Comment by Jericho** [comment]
This would be a great addition! Thanks for doing this.
