### ISSUE TITLE
Missing MeetingSettings continuous_meeting_chat

### ISSUE THREAD

**Issue by TheSupremeMonkey** [Jericho/ZoomNet#334]
There may be some other settings that are missing, but I know specifically that the continuous_meeting_chat settings are missing. 

https://developers.zoom.us/docs/api/rest/reference/zoom-api/methods/#operation/meetingCreate

**Comment by Jericho** [comment]
I made an effort last year to catch up with new fields that Zoom added to the MeetingSettings (see #291) and I also inventoried a few additional fields that need to be added (see #293). But it feels like a never ending race: every time I think I'm caught up, they add more fields.

Would you be able to help figuring out if there are any additional fields that we need to add and/or would you be able to submit a PR with some of these missing fields?

**Comment by TheSupremeMonkey** [comment]
I'm sure they're constantly changing this, so keeping up has to be a pain.
