### ISSUE TITLE
Additional fields in create

### ISSUE THREAD

**Issue by DonioT** [Jericho/ZoomNet#351]
Hi

I see there a bunch of fields that are available in zoom's create meeting request. Though only a few of them are available this libraries create.

How would i go about setting something like the meeting assistant id ? Would that be possible or would i need to do a custom implementation for these cases

**Comment by Jericho** [comment]
Can you list the fields that are missing from this library (and more importantly, point us to the documentation where there fields are listed)? As far as I know, this library allows you to specify all the documented fields when you create a new meeting therefore I don't think it's accurate for you to say that several fields are missing but I'll keep an open mind and wait for you to provide the list of fields that you think are missing.

I am aware of one field that is missing from the ZoomNet library when creating a meeting and a contributor was working on adding it to this library in #281 but unfortunately this effort seem to have been abandoned. 

Having said that, I know that Zoom updates their API from time to time which means that it's entirely possible that they made a change at some point that is not reflected in the ZoomNet library. If  you can point us to something specific that is missing from the ZoomNet library, I'll be happy to add it, and also feel free to contribute to this project 😉.

The specific example you mention, the "assistant id", is **NOT** a field that Zoom has documented as being available to set when you create a new meeting, as far as I know anyway. Can you please point to the documentation where you saw that Assistant Id is an available field?

**Comment by Jericho** [comment]
@DonioT I haven't heard back from you so I was wondering if you want to continue this discussion? Do you intend to provide the list of fields you think are missing?

**Comment by Jericho** [comment]
Closing this issue because I never heard back from @DonioT
