### ISSUE TITLE
Missing parameter in IMeeting.GetAsync method

### ISSUE THREAD

**Issue by sitkevich** [Jericho/ZoomNet#352]
Please add parameter _show_previous_occurrences_ to the API get metting method

https://developers.zoom.us/docs/meeting-sdk/apis/#operation/meeting

**Comment by Jericho** [comment]
Looks like a new parameter. Thanks for bringing it to my attention, I wasn't aware of it. They added the same parameter to "get webinar" as well.

**Comment by Jericho** [comment]
I have been experimenting with this new parameter when fetching a recuring meeting and indeed I can see that past occurrences are omitted from the result when this parameter is false and they are included when true. As you pointed out, the ZoomNet library currently does not allow you to configure this parameter to include past occurrences and therefore I understand why you requested this new feature.

I could certainly add a new boolean parameter to the `Meetings.GetAsync` method (and the `Webinars.GetAsync` as well) but here's an alternate idea: what if I don't add a new parameter to the `GetAsync` methods and instead I hardcode `show_previous_occurrences=true`. This would result in the past occurrences to always be included when fetching a recurring meeting, and the developer could choose to ignore these past occurrences if desired.

One reason why I am considering this alternate solution if that `GetAsync` is used to retrieve any type of meeting, not just recurring ones. But this new parameter would be useless, and in fact ignored, when fetching any other type of meeting (such as 'scheduled' for example). Couldn't this lead to confusion?

If we end up deciding to add this new parameter, I would add a note in the XML comments along these lines:

```csharp
/// <remarks>
/// Please note that this boolean parameter is applicable only when fetching a recurring meeting.
/// It will be ignored if you are fetching any other type of meeting such as scheduled, personal or instant for example.
/// </remarks>
```

Let me know what you think.

**Comment by sitkevich** [comment]
Personally, I only need the true parameter, and solved it with reflection. But for a library, it's better to have an optional parameter. You can add a default method parameter
GetAsync( ..., show_previous_occurrences=true, ...)
If someone wants, they can change it.

Thanks for quick response.

**Comment by Jericho** [comment]
I ended up adding an overload of the GetAsync method to avoid the confusion. Developers can use 
- `Task<Meeting> GetAsync(long meetingId, string occurrenceId = null, CancellationToken cancellationToken = default)` which will retrieve the meeting without past occurences. This matches the current behavior
- `Task<Meeting> GetAsync(long meetingId, string occurrenceId = null, bool includePreviousOccurrences = false, CancellationToken cancellationToken = default)` which allows developers to specify whether they want past occurrences to be included or not.

**Comment by Jericho** [comment]
I am preparing to release 0.79.0 which will include this enhancement.
