### ISSUE TITLE
Invalid authorization code exception when attempting to renew an authorization code

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#36]
When I designed the OAuth handler I was under the impression that we could reuse the authorization code every time we need a new access token and also when we need to renew the access token (this token is valid for 60 minutes, so it must be renewed regularly). That's the reason why you specify the connection information like so: 

```csharp
var connectionInfo = new OAuthConnectionInfo(clientId, clientSecret, authorizationCode);
```

I have recently realized that the authorization code can be used only one time in order to get an access token and a refresh token and the refresh token must be used subsequently to get a new access token and to refresh an expired token.

If you attempt to use the authorization a second time, you get the following exception: 
```json
{
    "reason": "Invalid authorization code xxxxxxxxxx_xxxxxxxxxxxxxxxxxxxxxx",
    "error": "invalid_request"
}
```

**Comment by Jericho** [comment]
@ashilon I know you are using OAuth so this bug is most likely affecting you

**Comment by ashilon** [comment]
> @ashilon I know you are using OAuth so this bug is most likely affecting you

It certainly does. Well, now I know why you why the constructor accepted the parameter. Thanks for fixing this bug.
