### ISSUE TITLE
ParticipantDevice missing

### ISSUE THREAD

**Issue by Iram1995** [Jericho/ZoomNet#381]
Hi,

I hope you’re doing well.
I’m encountering an error while syncing participants from Zoom into my CRM. I’ve already obtained latest the version from ZoomNet, but the issue persists.
Could you please assist me with this?
Thanks,
Iram
![image](https://github.com/user-attachments/assets/41741fb6-5801-46d7-981d-6feb13276760)
![image](https://github.com/user-attachments/assets/cfb16586-a87c-4fc7-8655-719de1fb2119)

**Comment by Jericho** [comment]
I told the Zoom person about the problem you are witnessing and they are asking for the following info:

> I am really sorry for the delay here…
I just re engaged with our Engineering team but what i want to do next, is to create another ticket an assign it to a different team. I would just need the name of the app you are using to call the API and the email associated with it so I can use that data to report the issue… could you provide that data?

Can you provide the name of your Zoom OAuth app and the email associated with it? If you prefer to communicated this info directly with the Zoom person, please email `elisa.levet _at_ zoom.us`

**Comment by Jericho** [comment]
Nevermind, the requested info is no longer necessary.

The Zoom team has acknowledged that there is an issue on their end and the `device` node is not intended to contain version information. It should contain values such as "Windows", not "Windows 10".

> we are currently working on reverting our logic back to only displayin the OS without the OS version 
 I am now waiting to hear back from the team to get an estimated timeline for this release

But I will still publish an update shortly to overcome the current issue you raised.

**Comment by Iram1995** [comment]
Thank you so much for quick fixes.

**Comment by Jericho** [comment]
Version 0.85.0 is being published as we speak and should be on NuGet.org within the next hour or so.
