### ISSUE TITLE
Id property of the Registrant model should be a string

### ISSUE THREAD

**Issue by rossacartwright** [Jericho/ZoomNet#42]

**Comment by Jericho** [comment]
I'll research this, but in the mean time can you show me a sample JSON you get from Zoom?

**Comment by AOPWoodbridge** [comment]
Sure, here's an example of a registrant from a webinar:

`{
   "page_count":5,
   "page_number":1,
   "page_size":30,
   "registrants":[
      {
         "address":"",
         "city":"",
         "comments":"",
         "country":"",
         "create_time":"2020-06-17T11:42:11Z",
         "custom_questions":[

         ],
         "email":"foo@bar.com",
         "first_name":"xx",
         "id":"8rl8DJtPQZO40ctjiGxfWw",
         "industry":"",
         "job_title":"",
         "join_url":"Foo",
         "last_name":"Bar",
         "no_of_employees":"",
         "org":"",
         "phone":"",
         "purchasing_time_frame":"",
         "role_in_purchase_process":"",
         "state":"",
         "status":"approved",
         "zip":""
      }
   ]
}`

**Comment by rossacartwright** [comment]
Sure, here's an example of a registrant from a webinar (retrieved via /webinars/{webinarId}/registrants)

```json
{
   "page_count":5,
   "page_number":1,
   "page_size":30,
   "registrants":[
      {
         "address":"",
         "city":"",
         "comments":"",
         "country":"",
         "create_time":"2020-06-17T11:42:11Z",
         "custom_questions":[

         ],
         "email":"foo@bar.com",
         "first_name":"Foo",
         "id":"8rl8DJtPQZO40ctjiGxfWw",
         "industry":"",
         "job_title":"",
         "join_url":"https://zoom.us/webinar",
         "last_name":"Bar",
         "no_of_employees":"",
         "org":"",
         "phone":"",
         "purchasing_time_frame":"",
         "role_in_purchase_process":"",
         "state":"",
         "status":"approved",
         "zip":""
      }
   ]
}
```

**Comment by Jericho** [comment]
Thank you both for the sample JSON. Based on why you provided, it’s quite clear that ID cannot be an integer and must be string. I’ll make the change.
