### ISSUE TITLE
Remove UserId parameter from this method

### ISSUE THREAD

**Issue by xantari** [Jericho/ZoomNet#44]
When you have a meeting ID it is globally unique. Remove the userId field from this method as it's not used and not needed.

https://github.com/Jericho/ZoomNet/blob/514c39867b0f3f390e361e204a1409d2c171d265/Source/ZoomNet/Resources/Meetings.cs#L210

**Comment by Jericho** [comment]
You're right, the `userId` parameter is useless in this instance. I'll remove it.
