### ISSUE TITLE
client.Meetings.GetAsync does not return all meeting information

### ISSUE THREAD

**Issue by xantari** [Jericho/ZoomNet#45]
When you get a meeting using GetAsync, it doesn't return the StartTime data of the meeting.

It seems that you need to return the proper type of meeting depending on the type of meeting.

In this case it should be ScheduledMeeting when the type is scheduled.

**Comment by Jericho** [comment]
The `Meeting.GetAsync` method is already designed to return a `InstantMeeting`, `ScheduledMeeting` or `RecurringMeeting` depending on the type of the meeting you are retrieving and all relevant properties should be populated. My guess is that you are simply not casting the retrieved meeting to the `ScheduledMeeting` class which would explain why you are not seeing the StartTime property; but this is just a guess on my part.

Here is the code sample I used to retrieve a scheduled meeting and to validate that the start date is populated as expected:

```csharp
var start = DateTime.UtcNow.AddMonths(1);
var duration = 30;
var settings = new MeetingSettings()
{
  ApprovalType = MeetingApprovalType.Manual
};
var trackingFields = new Dictionary<string, string>()
{
  { "field1", "value1"},
  { "field2", "value2"}
};

var newScheduledMeeting = await client.Meetings.CreateScheduledMeetingAsync(userId, "ZoomNet Integration Testing: scheduled meeting", "The agenda", start, duration, "p@ss!w0rd", settings, trackingFields, cancellationToken).ConfigureAwait(false);
await log.WriteLineAsync($"Scheduled meeting {newScheduledMeeting.Id} created").ConfigureAwait(false);

var scheduledMeeting = (ScheduledMeeting)await client.Meetings.GetAsync(newScheduledMeeting.Id, null, cancellationToken).ConfigureAwait(false);
await log.WriteLineAsync($"The meeting is scheduled to start on {scheduledMeeting.StartTime.ToLongDateString()} at {scheduledMeeting.StartTime.ToLongTimeString()}").ConfigureAwait(false);
```

Here is what gets displayed in the console:

![image](https://user-images.githubusercontent.com/112710/90439670-ebe27780-e0a3-11ea-9cde-a1e077e11915.png)

**Comment by xantari** [comment]
Ahh ok. Closing.
