### ISSUE TITLE
Get Zoom Meeting Info from URL

### ISSUE THREAD

**Issue by TonyValenti** [Jericho/ZoomNet#56]
Is there a way to get the Meeting Topic from a Zoom meeting with just the meeting room URL info?
Basically something like:

GetData("https://us02web.zoom.us/j/4921463591")

?

**Comment by Jericho** [comment]
To my knowledge Zoom API does not provide this functionality. However, The meeting id is included in the URL so you can use that to get all the details about the meetings.

**Comment by Jericho** [comment]
I hope I was able to answer your question.
