### ISSUE TITLE
No method for updating a scheduled meeting

### ISSUE THREAD

**Issue by AmSmart** [Jericho/ZoomNet#60]
There is currently no method that allows updating of an already scheduled meeting. I don't mind submitting a PR for it. I just need a go-ahead and contribution guidelines, if any.

**Comment by Jericho** [comment]
Yes feel free to submit PRs for any missing functionality. That would be greatly appreciated.

**Comment by absolute-git** [comment]
> There is currently no method that allows updating of an already scheduled meeting. I don't mind submitting a PR for it. I just need a go-ahead and contribution guidelines, if any.

This would be useful to me also, will you have time to submit the PR - any idea when?

Thanks in advance

**Comment by AmSmart** [comment]
Last week was a busy one for me, I'll look at opening a PR this week

**Comment by NickWright25** [comment]
Hi, is this a feature that's planned for an upcoming release?

I could do with this method too.

**Comment by Jericho** [comment]
@AmSmart are you still working on this? If not, I'll be happy to look into it but I want to make sure I don't duplicate your effort.

**Comment by Jericho** [comment]
Reading the documentation, I see that we need to able to 
- update a scheduled meeting
- update a recurring meeting
- update a recurring meeting's occurrence

**Comment by AmSmart** [comment]
I supposedly started working on it a while ago until I had too much to do on my desk. Regrettably, I haven't done much yet.

**Comment by AmSmart** [comment]
I actually need the feature(s) for a project that I'm working on and I'll be back on the project in January so it'll be a good time to add the features, except of course you want to go all-in right now.

**Comment by Jericho** [comment]
Thanks for letting me know. I'll take care of this feature.

**Comment by Jericho** [comment]
I just pushed a pre-release version to my [MyGet feed](https://www.myget.org/feed/jericho/package/nuget/ZoomNet). Let me know if you have an opportunity to test it and if you have any feedback.

**Comment by Jericho** [comment]
This new feature is released in version 0.11.0.
