### ISSUE TITLE
Page Number Deprecation

### ISSUE THREAD

**Issue by absolute-git** [Jericho/ZoomNet#62]
I have had some issue with the Internal.cs AsPaginatedResponse() because there's an expectation that page_number (and potentially page_count) exist in the response.

The API request I have been making (Meetings.GetAllAsync) dont return those values. so the method falls over.

Some of this problem is documented by Zoom https://marketplace.zoom.us/docs/guides/stay-up-to-date/announcements#batch-list-api-changes

Will this issue be fixed?

**Comment by Jericho** [comment]
This has already been [addressed](https://github.com/Jericho/ZoomNet/issues/46). 

Either you are using the `GetAllAsync` overload that's marked as "obsolete" (in which case you need to switch to overload that can handle paging tokens) or you are using an old version of the ZoomNet library where the paging issue had not been addressed (in which case you need to upgrade to the latest version and you need to switch to the overload that can handle paging tokens).

Hope this helps.

**Comment by absolute-git** [comment]
Ah thats brilliant, thanks for setting me straight :) You were right.

Typically the first method I tried out was obsolete *facepalm*

**Comment by Jericho** [comment]
Maybe I should remove all methods marked as obsolete in the next release to avoid this situation.
