### ISSUE TITLE
Webinar: Retrieving a webinar throws a serialisation error.

### ISSUE THREAD

**Issue by michael-aj-kennedy** [Jericho/ZoomNet#69]
Retrieving a single webinar causes a serialisation error when handling _authentication_option_ in WebinarSettings. Data type is listed in source as a nullable boolean, but Zoom API documentation reports it as being a string.

See: https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinar

**Comment by michael-aj-kennedy** [comment]
Fixed under pull req #70

**Comment by Jericho** [comment]
Nullable boolean is clearly the wrong data type indeed. I don't know what I was thinking???!!! Probably a "copy-paste" mistake on my part.

**Comment by Jericho** [comment]
On a related note: this fields contains the `Id` of the desired authentication type. Do you agree that it would make more sense for this field to be called `AuthenticationTypeId` rather than `AuthenticationType`?

**Comment by michael-aj-kennedy** [comment]
That sounds good to me, looked like it was returning some sort of hexadecimal code when I tested my changes (which did confuse me for a second), so naming it `AuthenticationTypeId` gives a clearer indication of what to expect.

**Comment by Jericho** [comment]
Excellent. I'll make the change and publish. Hopefully I'll get it done before lunch..

**Comment by michael-aj-kennedy** [comment]
Brilliant, thank you :)

**Comment by Jericho** [comment]
I will also add the following comment in XML documentation to explain what this Id corresponds to:

`The value of this field can be retrieved from the <see cref="AuthenticationOptions.Id"/> in the response of <see cref="IUsers.GetMeetingAuthenticationSettingsAsync"/>.`
