### ISSUE TITLE
CreateScheduledWebinarAsync incorrectly uses abstract Webinar type for deserialization

### ISSUE THREAD

**Issue by vyrotek** [Jericho/ZoomNet#75]
The CreateScheduledWebinarAsync method should be using the ScheduledWebinar type for deserialization. Here's a PR for the fix.

https://github.com/Jericho/ZoomNet/pull/74

**Comment by Jericho** [comment]
You're absolutely right.

**Comment by Jericho** [comment]
I just noticed that we forgot to modify the `IWebinars` interface as well. I'll take care of it.

**Comment by vyrotek** [comment]
@Jericho Thank you for the quick turn-around!
