### ISSUE TITLE
Create Webinar: Object cannot be instantiated

### ISSUE THREAD

**Issue by michael-aj-kennedy** [Jericho/ZoomNet#76]
When creating a new webinar, API command completes successfully, but ZoomNet throws an error reporting that ZoomNet.Models.Webinar cannot be instantiated.

`Could not create an instance of type ZoomNet.Models.Webinar. Type is an interface or abstract class and cannot be instantiated. Path 'uuid', line 1, position 8.`

**Comment by Jericho** [comment]
hummm. This sounds really similar to #75 which was resolved in [0.15.0](https://www.nuget.org/packages/ZoomNet/0.15.0) by #74
