### ISSUE TITLE
IMeetings.StartLiveStreamAsync returns ZoomException: Validation Failed.

### ISSUE THREAD

**Issue by nikola-kukic-az** [Jericho/ZoomNet#79]
There is issue with this method:

It should take as action 'start' (lowercase) and not 'Start'

Current method:

public Task StartLiveStreamAsync(long meetingId, bool displaySpeakerName, string speakerName, CancellationToken cancellationToken = default)
		{
			var data = new JObject()
			{
				{ "action", "Start" }, **-it should be: { "action", "start" }**
				{
					"settings", new JObject()
					{
						{ "active_speaker_name", displaySpeakerName },
						{ "display_name", speakerName }
					}
				}
			};

			return _client
				.PatchAsync($"meetings/{meetingId}/livestream/status")
				.WithJsonBody(data)
				.WithCancellationToken(cancellationToken)
				.AsMessage();
		}

According to documentation:

https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetinglivestreamstatusupdate

![image](https://user-images.githubusercontent.com/76776049/104920758-9682fd00-5998-11eb-98b8-f2e37258e8d3.png)

Regards

**Comment by Jericho** [comment]
Thank you for reporting this issue.
