### ISSUE TITLE
Webinars: Unable to edit existing webinars

### ISSUE THREAD

**Issue by michael-aj-kennedy** [Jericho/ZoomNet#80]
ZoomNet doesn't implement functionality to update webinars once they've been created.

As per documentation here: https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinarupdate

**Comment by Jericho** [comment]
Thank you so much for addressing this. I'm guessing you will model your code after the `Meetings.Update...` methods. It should be pretty similar I assume.

**Comment by michael-aj-kennedy** [comment]
> Thank you so much for addressing this. I'm guessing you will model your code after the `Meetings.Update...` methods. It should be pretty similar I assume.

Based my changes on the `Webinar.Create` method, but as you say, they're all pretty similar :)
