### ISSUE TITLE
Add method to return webinar template Id and names

### ISSUE THREAD

**Issue by MrSimonC** [Jericho/ZoomNet#90]
Create functionality to match the existing documented end point:
<https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/listwebinartemplates>

...whereby `templateIds` and `names` of (manually) created webinar templates can be returned, created under the authorised user against the request.

**Comment by Jericho** [comment]
I'm presuming you want to implement this change so I'm assigning this issue to you.

**Comment by MrSimonC** [comment]
Sounds good, thanks. Leave it with me.

**Comment by Jericho** [comment]
Thank you for taking care of this. I'm preparing a release today so this will be available shortly.
