### ISSUE TITLE
Allow Zoom TemplateId to be passed in when creating a recurring webinar

### ISSUE THREAD

**Issue by Jericho** [Jericho/ZoomNet#91]
Thanks to a recent [issue](#89) + [PR](#83) submitted by @MrSimonC, we can now use a template when creating a scheduled webinar. I suspect we can also use a template when creating a recurring webinar.

@MrSimonC, is this something you can verify? If it turns out that we can indeed use a template when creating a recurring webinar, do you want to implement this improvement?

**Comment by MrSimonC** [comment]
Absolutely no problem - I'll definitely look at this.
