### ISSUE TITLE
Reassign host missing

### ISSUE THREAD

**Issue by cesaramezcua** [Jericho/ZoomNet#92]
I detect that schedule_for is missing in UpdateScheduledMeetingAsync, this for me was necessary because I need to change the host by adding this, it works fine for me

![image](https://user-images.githubusercontent.com/1109561/105766979-0dcc0a00-5f20-11eb-85c5-21d568a2b014.png)

*It is necessary to have permissions for ScheduledMeeting 
Users.AddAssistantsByEmailAsync(string userId, IEnumerable<string> assistantEmails)

Regards!

**Comment by Jericho** [comment]
Yes you're right , the user Id is not being updated when updating a scheduled meeting and the same problem exists when updating a recurring meeting.

**Comment by Jericho** [comment]
My guess is that we have the same problem when updating a scheduled/recurring webinar. @michael-aj-kennedy is that something you can validate?

**Comment by michael-aj-kennedy** [comment]
> My guess is that we have the same problem when updating a scheduled/recurring webinar. @michael-aj-kennedy is that something you can validate? Although, the documentation doesn't mention anything about the `Webinar.schedule_for` being updatable so maybe it's not an issue when updating a webinar???

Like you, I would've assumed that webinars are based on the same underlying data structure at the Zoom end. Unfortunately we've only been provided with a single user capable of using webinar functionality (zoom charges on a per-user basis) so I can't perform a proper test of this.

However the `schedule_for` param is missing from both webinar create & update commands which implies that the functionality was deliberately omitted from webinars (perhaps on account of it being a paid feature and therefore not applicable to all users)

We're providing our users with a dropdown list of available webinar users (by querying Zoom users & filtering by licence type) to achieve what I assume would be a similar result.
